theme = "gruvbox_dark_hard"

[editor]
line-number = "relative"
cursorline = true
color-modes = true
auto-save = true
mouse = true
end-of-line-diagnostics = "hint"
# bufferline = "multiple"

[editor.inline-diagnostics]
cursor-line = "hint"
other-lines = "hint"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true

[editor.file-picker]
hidden = false

[editor.statusline]
center = [
  "version-control",
  "diagnostics",
  "selections",
  "position",
  "file-encoding",
  "file-line-ending",
  "file-type",
]

# [editor.statusline]
# right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]

[editor.lsp]
display-messages = true
display-inlay-hints = true

[editor.gutters]
layout = ["diff", "diagnostics", "line-numbers", "spacer"]

[keys.normal]
C-g = [
  ":write-all",
  ":new",
  ":insert-output lazygit",
  ":set mouse false",       # First disable mouse to hint helix into activating it
  ":set mouse true",
  ":buffer-close!",
  ":redraw",
  ":reload-all",
]

C-b = ":sh git log -n 5 --format='format:%%h (%%an: %%ar) %%s' --no-patch -L%{cursor_line},+1:%{buffer_name}"
