theme = "catppuccin_latte"

[editor]
line-number ="absolute"
cursorline = true
color-modes = true
auto-save = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true

